---
- name: Install and setup attestation service
  ansible.builtin.include_tasks: install-attestation-service.yml
  tags: attestation-service

- name: Configure attestation service
  ansible.builtin.include_tasks: configure-attestation-service.yml
  tags: attestation-service