# ansible/k3s/roles/admission-controller/defaults/main.yml

# Git repository settings
sek8s_repo: "https://github.com/chutsai/sek8s"
seks8_version: "attest"
update_repository: true
update_dependencies: false