---
- name: GPU Device Setup
  ansible.builtin.include_tasks: device-setup.yml
  tags: gpu-device-setup

- name: K3s GPU Setup
  ansible.builtin.include_tasks: k3s-setup.yml
  tags: k3s-gpu-setup

- name: Install PPCIe service
  ansible.builtin.include_tasks: install-ppcie-service.yml
  tags: install-ppcie-service