---
- name: Cleanup k3s
  ansible.builtin.include_task: cleanup-k3s.yml

- name: Cleanup cloud-init
  ansible.builtin.include_task: cleanup-cloud-init.yml

- name: Cleanup system
  ansible.builtin.include_task: cleanup-system.yml
  